"""Refactored models with indexes and constraints

Revision ID: 421a6024d18c
Revises: d70b981fa9c5
Create Date: 2026-01-08 12:03:34.715415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421a6024d18c'
down_revision = 'd70b981fa9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('service_professionals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_professionals_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_professionals_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_professionals_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_requests_date_of_request'), ['date_of_request'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requests_date_of_request'))

    with op.batch_alter_table('service_professionals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_professionals_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_professionals_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_professionals_is_verified'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))

    # ### end Alembic commands ###
